### ISSUE TITLE
No challenge is required to use account!

### ISSUE THREAD

**Issue by Pauly24** [igdmapps/igdm-pro-release#1]
When I try to login with some of my instagram accounts it just says "No challenge is required to use account!"

I'm guessing it has something to do with step up authentication? But can't find anything on how to fix it.

Regards.

**Comment by ifedapoolarewaju** [comment]
Hi,

Usually this happens when you try to login from a new device or location. If you restart the app and try to login again it should work.

Please let me know how that goes.

**Comment by andrefedev** [comment]
something that helped me, was entering the App from my cell phone and I gave it authorization and it worked.

**Comment by ifedapoolarewaju** [comment]
this is fixed now. please restart your app to install the latest update
