### ISSUE TITLE
Emoticons wrong charset

### ISSUE THREAD

**Issue by gabbian0** [igdmapps/igdm-pro-release#16]
This is what i see when i open the emoticon tab

![image](https://user-images.githubusercontent.com/36705490/57459757-20963b00-7274-11e9-84d9-e79d1038dc1b.png)

**Comment by EnolCook** [comment]
Same problem here, any way to fix that ?

**Comment by ifedapoolarewaju** [comment]
hi there, do you mind telling what version of windows you are running?

**Comment by ifedapoolarewaju** [comment]
closing this issue as duplicate to https://github.com/ifedapoolarewaju/igdm-pro-release/issues/7
