### ISSUE TITLE
emojis wont work 

### ISSUE THREAD

**Issue by ewkeelyn** [igdmapps/igdm-pro-release#19]
i dont know anything about coding but most, not all, but most, of the emojis are showing up as question marks and i have to click on it and put it in the message to see what it is. idk if im just dumb and this is because im still using the free trial or if something is wrong, pls help

**Comment by ifedapoolarewaju** [comment]
closing this issue as duplicate to https://github.com/ifedapoolarewaju/igdm-pro-release/issues/7
