### ISSUE TITLE
Cannot upload jpg

### ISSUE THREAD

**Issue by romanmorozov81** [igdmapps/igdm-pro-release#20]
I cannot send jpg, always get the message - Upload failed, please ensure that file in jpg format

**Comment by ifedapoolarewaju** [comment]
is the image originally a jpg image or was it converted somehow?

**Comment by romanmorozov81** [comment]
no it's original. Screenshot for example. Some time ago, it was sending without problems. I've tested more. If image is small size about 80kb and small resolution it's ok , but file 900kb no. Just bought PRO thought it's limitation of free version. But it's the same. It's very important for my business.
The example of file 

![Screenshot 2019-07-18 в 11 17 09](https://user-images.githubusercontent.com/43423437/61441653-c0480780-a94e-11e9-9054-bc3d39aa3d1e.jpg)

**Comment by romanmorozov81** [comment]
Strange, I've tested the another  big screenshot it's ok.

**Comment by ifedapoolarewaju** [comment]
hmm, maybe some files need compressing because IG has a file size limit. I'll look into it! Thank you for reporting!

**Comment by romanmorozov81** [comment]
Looks like it's about proportions or resolution, 
if the resolution is 2880x1800 992kb it's OK
if the resolution 2880x1666 930kb it's not

**Comment by ifedapoolarewaju** [comment]
ok, I think compression should help with that too

**Comment by romanmorozov81** [comment]
Still cannot send some jpg files. 2 updates passed, but no luck. Especially I cannot send screenshots made on Mac. I't very important for my business. Compression doesn't help. Changing resolution also. You can test it. It's just simple screenshot from Macbook Pro without touch.
![Screenshot 2019-08-22 в 22 32 42](https://user-images.githubusercontent.com/43423437/63544104-f7e93700-c52c-11e9-8cd7-d6dfef54af55.jpg)
