### ISSUE TITLE
media

### ISSUE THREAD

**Issue by aerfile** [igdmapps/igdm-pro-release#23]
hello, 
i have last versions of igm pro, i cant see media message unsupported/message

<img width="441" alt="Schermata 2019-08-04 alle 13 02 43" src="https://user-images.githubusercontent.com/53695218/62422788-45098400-b6b8-11e9-9f60-dfac2a391865.png">

**Comment by ifedapoolarewaju** [comment]
Hi do you know what kind of message/file was sent to you?

**Comment by aerfile** [comment]
audio, pic, video, every



Andrea Raffa
andrearaffa@me.com




> Il giorno 4 ago 2019, alle ore 13:17, Ifedapo .A. Olarewaju <notifications@github.com> ha scritto:
> 
> Hi do you know what kind of message/file was sent to you?
>

**Comment by aerfile** [comment]
Andrea Raffa
DJ & PRODUCER

info@andrearaffa.dj
www.andrearaffa.dj

> Il giorno 4 ago 2019, alle ore 13:17, Ifedapo .A. Olarewaju <notifications@github.com> ha scritto:
> 
> Hi do you know what kind of message/file was sent to you?
>
