### ISSUE TITLE
Autoupdate no work

### ISSUE THREAD

**Issue by gloriosky** [igdmapps/igdm-pro-release#24]
When I open IGDM, it print this message:
Update has failed! :)
How can I update messages?
Thanks

**Comment by ifedapoolarewaju** [comment]
Are you using a windows machine? Or Linux? Or MacOS? Also what version do you have currently running? If it helps, you could just install a fresh version from here https://pro.igdm.me

**Comment by ifedapoolarewaju** [comment]
this is fixed now
