### ISSUE TITLE
Broken: Switching between chats

### ISSUE THREAD

**Issue by joelsprechman** [igdmapps/igdm-pro-release#27]
Short video showing the problem

https://www.loom.com/share/716c281ac9c44c3c99cee21bf520bc55

thanks

**Comment by ifedapoolarewaju** [comment]
does this issue still occur?

**Comment by joelsprechman** [comment]
yes. Also, how do I check my version? Whenever it tries to Autoaupdate it
always ends with: Update has failed! :(

**Comment by ifedapoolarewaju** [comment]
> how do I check my version

Are you on windows or Mac? On Mac click the app name on the menu bar, and click "About". Something similar should exist on the windows version.

> Whenever it tries to Autoaupdate it always ends with: Update has failed! :(

The version you have probably has a broken `autoupdate` implementation.
do you mind installing the latest directly from the website? Just re-enter your License key (if it prompts you) after it has been installed.

**Comment by joelsprechman** [comment]
reinstalling worked!  Thanks! Will let you know about next update .

Did the ability to use mouse scroll up/down go away or was that never a
feature?
