### ISSUE TITLE
Scroll isn't working

### ISSUE THREAD

**Issue by rikillerena** [igdmapps/igdm-pro-release#28]
Hello, I would like to report that the mouse scroll in IGDM pro does not work as I did in IGDM, I would like you to fix this error (also because I paid for the product and so far I have loved it)

**Comment by ifedapoolarewaju** [comment]
Hi there, could you provide some more description on how to reproduce this issue? Also could you share what version of the app you are using and what operating system you are running?

**Comment by rikillerena** [comment]
I'm using the version 1.4.0 in a laptop Windows 10, the problem is that when I want to go up and down in a conversation or when I'm looking for a chat, the scroll of the mouse doesn't work, I have to click and slide the lateral bar and is kinda annoying

**Comment by ejarro** [comment]
I'm having the same issue, and so far, even by grabing the side bar the scroll is not working and get back to initial (up) position...

Windows pro 10, v1909 - IGdm pro v1.4.1

**Comment by ifedapoolarewaju** [comment]
@rikillerena is it possible you provide a screenshot, or a screencast for this? I'm having a hard time getting the full picture of this issue.

**Comment by spoorun** [comment]
We have the same issue.
We're using Linux Arch with KDE Plasma
The (very thin) scrollbar works if it is clicked on a dragged up or down.
However, scrolling using the touchpad and two-finger scrolling does nothing at all.
