### ISSUE TITLE
Empty list of chat

### ISSUE THREAD

**Issue by ejarro** [igdmapps/igdm-pro-release#30]
![screenshot](https://user-images.githubusercontent.com/39911554/73929575-559fee80-48d5-11ea-946c-c1b66df5916d.png)
I am running  IGdm pro 1.4.1 on Windows 10 pro - v.1909.
After trying to restart, my list of chat is still empty as you can see on enclosed screenshot.

I bought it yesterday and worked fine until today. If someone send a message when I'm on it, it seems to work though. Meaning I will see new messages, but not all the others.

Also, there is no button to disconnect, I wanted to try to disconnect then reconnect. Should I try to reinstall the app? But a feature to disconnect could be useful! As well as a feature to like message (not only quote ;) )

**Comment by ejarro** [comment]
Short update, out of the blue the list refreshed of chat and shown up. 
Let's let the bug open, I will close the issue if within a week it doesn't occur anymore.

Though a disconnect feature and like message could be a nice plus.
Also the scrolling bug already open in the list of issue is quite anoying. Otherwise great job ;)

**Comment by ifedapoolarewaju** [comment]
Hi @ejarro, thank you for reporting this issue.

> Also, there is no button to disconnect

by _disconnect_ do you mean _unfollow_?

**Comment by ejarro** [comment]
By disconnect I mean to log out.  
Because maybe loging out and then loging in back, could solve those kind of issue meanwhile a proper fix is release in next version.

**Comment by ifedapoolarewaju** [comment]
there is a feature to logout already. If you hover on your profile photo, you will see the option to logout in a dropdown.

**Comment by ejarro** [comment]
Thanks I just found it, but somehow was not working until now. It seems like it take some times to initialize everything.
Not sure if it's comming from instagram (maybe to put in cache everything) or some API calls which get stuck for a while.

But for now I'm experiencing no more bugs! Thanks for your support I close the bug.
(may worth a quick investigation on those delay to have the app fully operational)
