### ISSUE TITLE
I CANOT USE MI ACCOUNT

### ISSUE THREAD

**Issue by FITMESW** [igdmapps/igdm-pro-release#41]
Hi, i already buy my license, and add it to de app, but i try to log in to my IG account and appears this: POST /api/v1/accounts/login/ - 500 Internal Server Error;

**Comment by ifedapoolarewaju** [comment]
Hi do you get this same error if you restart the app and try again?

**Comment by FITMESW** [comment]
let me try

**Comment by FITMESW** [comment]
yes, it say the same

**Comment by FITMESW** [comment]
thanks, its already working

**Comment by ifedapoolarewaju** [comment]
I just tried to login and it worked for me.

what version of IGdm Pro are you using?
Are you using it with Proxy?
What type of machine are you using?
Also can you try with a different account (if you have one)?

**Comment by ifedapoolarewaju** [comment]
ah just saw your comment
