### ISSUE TITLE
IGdm Pro 

### ISSUE THREAD

**Issue by wolfiewoofpup** [igdmapps/igdm-pro-release#42]
The app is not showing my messages, it worked yesterday but today it is not working.

**Comment by ifedapoolarewaju** [comment]
Hi, is this still the case for you? What exactly isn't showing? Screenshots will be helpful too

**Comment by wolfiewoofpup** [comment]
Yes, it is still not working

**Comment by wolfiewoofpup** [comment]
I will get a screenshot

**Comment by wolfiewoofpup** [comment]
![image](https://user-images.githubusercontent.com/70702851/92146941-71765f00-ede8-11ea-9409-c14a7304a7d2.png)
 It is not showing my messages at all

**Comment by ifedapoolarewaju** [comment]
I would say try logging out and log back in

**Comment by wolfiewoofpup** [comment]
I have tried that and it still doesn't work

**Comment by ifedapoolarewaju** [comment]
did you recently change password or enable 2-factor authentication or anything? Do you have other accounts that you can login with to see if they work?

**Comment by wolfiewoofpup** [comment]
I have not changed my password or enabled 2 factor authentication. I do not
have an another account

**Comment by wolfiewoofpup** [comment]
It worked now
