### ISSUE TITLE
5 minutes after every login Instagram says i might have logged in to a phishing site

### ISSUE THREAD

**Issue by atcasanova** [igdmapps/igdm-pro-release#46]
And then logs me out of my phone app and doesn't let me log in again unless I change my password. The IGdm Pro session is then killed. Please fix it.

**Comment by ClwnMan76** [comment]
I just got the same thing. Made me verify and change my password.

**Comment by atcasanova** [comment]
Still waiting for an update about this. I bought the Pro version and can't use it

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version

**Comment by atcasanova** [comment]
So, i've tried to input my license - the one i bought in 2021 - and:

![image](https://github.com/igdmapps/igdm-pro-release/assets/2973929/a5293a39-7177-4b07-8b92-a70e18221fc0)

**Comment by ifedapoolarewaju** [comment]
Hi @atcasanova could you please share the email address with which you purchased the License?

You can send it to me via email (i****m) if you'd prefer not to post it here.

**Comment by atcasanova** [comment]
Just sent it to you

**Comment by ifedapoolarewaju** [comment]
Hi @atcasanova I sent you an email yesterday, but I'm not sure if you saw it (it may have ended up in your spam)
