### ISSUE TITLE
I just bought pro IGDM and can't sign in.

### ISSUE THREAD

**Issue by carlosrodolfogonzalez** [igdmapps/igdm-pro-release#48]
i've using test version but i already bougth pro version, but cant sign in!! just keeps me waiting. 

heeelp.

**Comment by ifedapoolarewaju** [comment]
What version of IGdm Pro are you running?

*Ifedapo Olarewaju | Software Engineer*

**Comment by spinalgr1990** [comment]
I have the same problem here

**Comment by carlosrodolfogonzalez** [comment]
I'm using 2.0.2.

**Comment by spinalgr1990** [comment]
![error](https://user-images.githubusercontent.com/63348163/116715285-3d872400-a9df-11eb-8641-24677387eedd.png)

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
