### ISSUE TITLE
IGDM not showing profile pictures, nor media messages

### ISSUE THREAD

**Issue by yogzo1** [igdmapps/igdm-pro-release#50]
IGDM not showing profile pictures, nor media messages

**Comment by ifedapoolarewaju** [comment]
Yes this is a recent issue. We are looking to fix it soon

**Comment by maurawa** [comment]
> Yes this is a recent issue. We are looking to fix it soon
> […](#)
> On 30 Apr 2021, at 18:45, yogzo1 ***@***.***> wrote: ﻿ IGDM not showing profile pictures, nor media messages — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Having the same issue - is there a way to fix it or is it programs fault?

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
