### ISSUE TITLE
IGDM-Pro shows error whenever i send a message on linux

### ISSUE THREAD

**Issue by atcasanova** [igdmapps/igdm-pro-release#51]
Image attached

![2021-05-04_14-53](https://user-images.githubusercontent.com/2973929/117047774-a248c400-ace8-11eb-9804-a5e23d705acd.png)

**Comment by atcasanova** [comment]
Updated and still won't work.

**Comment by manujarr** [comment]
Same issue on windows, seems like there is no maintenance anymore....

**Comment by atcasanova** [comment]
Dude is selling this and won't even bother to reply

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
