### ISSUE TITLE
Pics and video doesn't work

### ISSUE THREAD

**Issue by paulorsotto** [igdmapps/igdm-pro-release#52]
I can't display profile icons, pics and videos on Windows 10. If I save pics or copy URL it works with pics, but not with videos. Please help me
![Clip](https://user-images.githubusercontent.com/84278964/118402025-5f7fd800-b668-11eb-95fe-e6fb390bb476.jpg)

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
