### ISSUE TITLE
Pictures issue

### ISSUE THREAD

**Issue by JotaPeee04** [igdmapps/igdm-pro-release#54]
In Igdm and Igdm pro, I have this problem that I can't see any of the photos I recieve and Idk if it's just me or if there is a way to fix it.

**Comment by manujarr** [comment]
Same issue on my side!

**Comment by Anzio1000** [comment]
Same - no images showing for both profile and in messages  
Windows 10

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
