### ISSUE TITLE
why appears this?

### ISSUE THREAD

**Issue by mikab3** [igdmapps/igdm-pro-release#59]
![image](https://user-images.githubusercontent.com/93885048/140661569-675b62f2-230d-4322-ab1f-cdd16daf0602.png)

**Comment by spinalgr1990** [comment]
I have also the same problem..

**Comment by sylver2021** [comment]
I have this problem aswell
![Screenshot (663)](https://user-images.githubusercontent.com/94618937/142420570-9867252d-714c-4400-b99b-1af51f393cd1.png)

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
