### ISSUE TITLE
request url

### ISSUE THREAD

**Issue by shehsybil** [igdmapps/igdm-pro-release#6]
hi, i want to know the request url you using to delete a thread (dm conversation) 

'direct_v2/threads/{thread_id}/items/{item_id}/delete/' this url delete only item in thread (a message) but not the thread.

please give me the url, i can donate for this

**Comment by ifedapoolarewaju** [comment]
there's already a feature to delete a thread. If you right click on the conversation from the list of the conversations on the left, you will see the option to delete conversation
