### ISSUE TITLE
Issue with IGDM 

### ISSUE THREAD

**Issue by sylver2021** [igdmapps/igdm-pro-release#60]
Hello,

I hope all is well, I am really keen to purchase this app for my other computers, but I keep getting this error code when I am trying to send a message, 

can you please let me know how I can fix this?
![Screenshot (663)](https://user-images.githubusercontent.com/94618937/142420109-87cace24-506e-412b-9656-e8a2f90eb929.png)

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
