### ISSUE TITLE
Help, fail to Login

### ISSUE THREAD

**Issue by Rengui0** [igdmapps/igdm-pro-release#65]
![image](https://user-images.githubusercontent.com/97323673/156562659-b7b103cc-536c-45a4-9e00-dbac3bd4bc3c.png)

Error: GET /api/v1/fbsearch/suggested_searches/?type=users - 560 -;

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
