### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by paulorsotto** [igdmapps/igdm-pro-release#66]
I receive this error when trying to login with my credentials (writint them without copy and paste!!!)

/api/v1/fbsearch/suggested_searches/?type=blended - 404 Not Found;

**Comment by paulorsotto** [comment]
![Clip](https://user-images.githubusercontent.com/84278964/161063541-cf0962a1-9a6f-4ad4-a254-64d1e941a235.jpg)

**Comment by paulorsotto** [comment]
No proxy

**Comment by joelsprechman** [comment]
@paulorsotto  - How did u resolve?
