### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by joelsprechman** [igdmapps/igdm-pro-release#68]
Hi. Have not used app in a while. Tried today. Updated to latest version windows 10 and can not log in

GET /api/v1/fbsearch/suggested_searches/?type=users - 404 Not Found;

though IG sent me email that I logged in via this device? Samsung SM-A605FN

Help! Thanks.

**Comment by joelsprechman** [comment]
License is active

**Comment by ifedapoolarewaju** [comment]
Hi, a new version of IGdm Pro that fixes this issue has now been released.

Please visit https://pro.igdm.me/ to download the latest version
