### ISSUE TITLE
IGDM Pro with problem at emoticons

### ISSUE THREAD

**Issue by cassiagraota** [igdmapps/igdm-pro-release#7]
I can't see the emoticons....

![igdm emoticons](https://user-images.githubusercontent.com/49911496/56586524-40600a80-65b6-11e9-9b83-de815be0a4d3.jpeg)

**Comment by JDNostalgia** [comment]
I can't see them either. I just got IG DM Pro today and feel ripped off. The only new feature was being able to delete messages. There is no dark theme as advertised: https://pro.igdm.me/ Waste of 10 Euros.

**Comment by ifedapoolarewaju** [comment]
> There is no dark theme as advertised

@JDNostalgia There is a dark theme feature available if you click the `Settings` menu under your profile, you will see an option to `Enable Dark theme`.

All features advertised for IGdm Pro are genuinely available. The issue with emoticons is simply an error that will be fixed soon.

**Comment by JDNostalgia** [comment]
I found the feature, thank you. Apologies for my overreaction. I have been using IGDM for a year and I found it useful and that is why I purchased the pro version.

Two features that would be great to add in the future if possible would be the ability to copy links, such as sending a youtube video link. Also the ability to view video messages would be great. I've noticed over the time using IGDM in conversations only certain types of media are recognised and often the message ''unsupported message format'' will come up which is a bit embarrassing when someone is sharing something with you but you have no idea what the file is.

**Comment by ifedapoolarewaju** [comment]
> I have been using IGDM for a year and I found it useful and that is why I purchased the pro version

Thank you for the patronage :)

> the ability to copy links, such as sending a youtube video link.

@JDNostalgia but this is already possible no?

> I've noticed over the time using IGDM in conversations only certain types of media are recognised and often the message ''unsupported message format''

On IGdm Pro, nearly all media messages are displayed appropriately. This is part of the benefits that IGdm Pro offers

**Comment by JDNostalgia** [comment]
The links don't work for now. I tested it just now to confirm. I copied a Youtube link, but there is no option to paste and send it in IGDM conversations.

**Comment by ifedapoolarewaju** [comment]
@JDNostalgia oh so you mean when you right-click, you don't see an option to paste? If that's what you are referring to, then you are right, I'll take a note of this. The workaround, for now, is to use commands (i.e CMD+v for macOS or Ctrl+v for windows) to paste the link.

**Comment by JDNostalgia** [comment]
Yes. I wasn't aware of the Ctrl+v command, thanks. 

At the moment I am having signing in issues. When I click on the the desktop app it won't start. I've tried restarting the computer but nothing. I even re-downloaded regular IGDM because I couldn't access my messages. All other desktop applications are working fine. It has only stopped working in the past hour.

**Comment by ifedapoolarewaju** [comment]
Does it give any error when you try to start it? Does it display any window?

**Comment by JDNostalgia** [comment]
No, I just click on it and nothing happens. I originally thought it was because of an update but I guess not.

**Comment by ifedapoolarewaju** [comment]
@JDNostalgia the sign in issue is fixed now. Please start your app and see that it works.

**Comment by JDNostalgia** [comment]
It's working again, thanks. 

One last question. Is it possible to save any photos sent through IGDM and is there any command to do so? The only way I can think of now is to screenshot but that is slow.
