### ISSUE TITLE
Login failed. Please try again. If this issue persists, please contact the developer.

### ISSUE THREAD

**Issue by uiltonlopes** [igdmapps/igdm-pro-release#78]
![Captura de Tela 2024-10-22 às 15 35 37](https://github.com/user-attachments/assets/67b3abb2-78af-4957-9e4a-a8d2987f9131)

**Comment by ifedapoolarewaju** [comment]
Hi @uiltonlopes sorry to hear that you are having issues with this.

What version of macOS are you running?
Also is your MacBook an M1 or Intel?

**Comment by uiltonlopes** [comment]
Chip: Apple M1 
MacOS: 15.0.1 (24A348)

**Comment by ifedapoolarewaju** [comment]
Hi @uiltonlopes this seems to be an issue with macOS Sequoia.
I have just released a new version v3.4.0 that resolves this.

You can find it on the website https://pro.igdm.me or:

restart your IGdm Pro app, wait for about 5 minutes so it downloads the latest version, then restart it again so it's automatically installed.

Please let me know if it works for you afterwards

**Comment by uiltonlopes** [comment]
Tks, its working <3

**Comment by ifedapoolarewaju** [comment]
Great to hear! 🎉 

If you wouldn't mind, could you be so kind to leave a review on Product Hunt?
https://www.producthunt.com/products/igdm/reviews/new

It will mean a great deal. Thank you in advance.
